//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrangeJuice.Server.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public System.Guid RequestId { get; set; }
        public string Url { get; set; }
        public string HttpMethod { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
    }
}
